### ISSUE TITLE
Some bugs

### ISSUE THREAD

**Issue by MatheusGrilo** [TheTrain2000/UltimateBraveryBatch#1]
Hey, I'd like to know if it's hard to fix some "problems".

1st. You can't make more than 1 sup item;
2nd. You can't build _Hydras_ for ranged champions or _Runnan_ for melee champions;
3rd. I don't know if it's a bug, but would be cool if the items didn't repeat on same build.

Thank you so much, I really enjoy this :)

**Comment by tylergibbs2** [comment]
Thanks for enjoying the program :)

Knowing that there are still people that enjoy using this really make my day, and this comment inspired me to start the rewrite. You can check my progress over at the rewrite branch. The rewrite should fix all the bugs you listed.

**Comment by tylergibbs2** [comment]
Alright, the rewrite is complete. Some features are missing that I didn't think would be missed, but if they are let me know (Team Bravery). The rewrite features room for expansion which the old version of the program didn't. If you already have it downloaded, load it up and it should ask to update. If not, re-download from the GitHub.
